/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSafetyRouteImport } from './routes/app.safety'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppDriverRouteImport } from './routes/app.driver'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppCirclesRouteImport } from './routes/app.circles'
import { Route as AppRideNewRouteImport } from './routes/app.ride.new'
import { Route as AppRideRideIdRouteImport } from './routes/app.ride.$rideId'
import { Route as AppDriverTripsRouteImport } from './routes/app.driver.trips'
import { Route as AppDriverOnboardingRouteImport } from './routes/app.driver.onboarding'
import { Route as AppDriverEarningsRouteImport } from './routes/app.driver.earnings'
import { Route as AppChatConversationIdRouteImport } from './routes/app.chat.$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppRideNewRoute = AppRideNewRouteImport.update({
  id: '/ride/new',
  path: '/ride/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRideRideIdRoute = AppRideRideIdRouteImport.update({
  id: '/ride/$rideId',
  path: '/ride/$rideId',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverTripsRoute = AppDriverTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppDriverRoute,
} as any)
const AppDriverOnboardingRoute = AppDriverOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppDriverRoute,
} as any)
const AppDriverEarningsRoute = AppDriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppDriverRoute,
} as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/driver': typeof AppDriverRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/app/driver/earnings': typeof AppDriverEarningsRoute
  '/app/driver/onboarding': typeof AppDriverOnboardingRoute
  '/app/driver/trips': typeof AppDriverTripsRoute
  '/app/ride/$rideId': typeof AppRideRideIdRoute
  '/app/ride/new': typeof AppRideNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/driver': typeof AppDriverRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/app/driver/earnings': typeof AppDriverEarningsRoute
  '/app/driver/onboarding': typeof AppDriverOnboardingRoute
  '/app/driver/trips': typeof AppDriverTripsRoute
  '/app/ride/$rideId': typeof AppRideRideIdRoute
  '/app/ride/new': typeof AppRideNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/driver': typeof AppDriverRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/app/driver/earnings': typeof AppDriverEarningsRoute
  '/app/driver/onboarding': typeof AppDriverOnboardingRoute
  '/app/driver/trips': typeof AppDriverTripsRoute
  '/app/ride/$rideId': typeof AppRideRideIdRoute
  '/app/ride/new': typeof AppRideNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/circles'
    | '/app/contracts'
    | '/app/driver'
    | '/app/messages'
    | '/app/safety'
    | '/app/settings'
    | '/app/'
    | '/app/chat/$conversationId'
    | '/app/driver/earnings'
    | '/app/driver/onboarding'
    | '/app/driver/trips'
    | '/app/ride/$rideId'
    | '/app/ride/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/circles'
    | '/app/contracts'
    | '/app/driver'
    | '/app/messages'
    | '/app/safety'
    | '/app/settings'
    | '/app'
    | '/app/chat/$conversationId'
    | '/app/driver/earnings'
    | '/app/driver/onboarding'
    | '/app/driver/trips'
    | '/app/ride/$rideId'
    | '/app/ride/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/circles'
    | '/app/contracts'
    | '/app/driver'
    | '/app/messages'
    | '/app/safety'
    | '/app/settings'
    | '/app/'
    | '/app/chat/$conversationId'
    | '/app/driver/earnings'
    | '/app/driver/onboarding'
    | '/app/driver/trips'
    | '/app/ride/$rideId'
    | '/app/ride/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver': {
      id: '/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/circles': {
      id: '/app/circles'
      path: '/circles'
      fullPath: '/app/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ride/new': {
      id: '/app/ride/new'
      path: '/ride/new'
      fullPath: '/app/ride/new'
      preLoaderRoute: typeof AppRideNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ride/$rideId': {
      id: '/app/ride/$rideId'
      path: '/ride/$rideId'
      fullPath: '/app/ride/$rideId'
      preLoaderRoute: typeof AppRideRideIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver/trips': {
      id: '/app/driver/trips'
      path: '/trips'
      fullPath: '/app/driver/trips'
      preLoaderRoute: typeof AppDriverTripsRouteImport
      parentRoute: typeof AppDriverRoute
    }
    '/app/driver/onboarding': {
      id: '/app/driver/onboarding'
      path: '/onboarding'
      fullPath: '/app/driver/onboarding'
      preLoaderRoute: typeof AppDriverOnboardingRouteImport
      parentRoute: typeof AppDriverRoute
    }
    '/app/driver/earnings': {
      id: '/app/driver/earnings'
      path: '/earnings'
      fullPath: '/app/driver/earnings'
      preLoaderRoute: typeof AppDriverEarningsRouteImport
      parentRoute: typeof AppDriverRoute
    }
    '/app/chat/$conversationId': {
      id: '/app/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/app/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDriverRouteChildren {
  AppDriverEarningsRoute: typeof AppDriverEarningsRoute
  AppDriverOnboardingRoute: typeof AppDriverOnboardingRoute
  AppDriverTripsRoute: typeof AppDriverTripsRoute
}

const AppDriverRouteChildren: AppDriverRouteChildren = {
  AppDriverEarningsRoute: AppDriverEarningsRoute,
  AppDriverOnboardingRoute: AppDriverOnboardingRoute,
  AppDriverTripsRoute: AppDriverTripsRoute,
}

const AppDriverRouteWithChildren = AppDriverRoute._addFileChildren(
  AppDriverRouteChildren,
)

interface AppRouteChildren {
  AppCirclesRoute: typeof AppCirclesRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDriverRoute: typeof AppDriverRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppRideRideIdRoute: typeof AppRideRideIdRoute
  AppRideNewRoute: typeof AppRideNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCirclesRoute: AppCirclesRoute,
  AppContractsRoute: AppContractsRoute,
  AppDriverRoute: AppDriverRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppRideRideIdRoute: AppRideRideIdRoute,
  AppRideNewRoute: AppRideNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
